name: "Install Hello World Library"
description: "Installs the Hello World Library"
inputs:
  install_location: 
    description: "Full path to where the library should be installed"
    required: false
    default: $HOME/install
  do_checkout:
    description: "Do we need to checkout Hello World Library?"
    required: false
    default: true
runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      if: ${{ inputs.do_checkout }}
      uses: actions/checkout@v4
      with:
        repository: MultiprojectDevOps/hello_world_library
    - name: Get Compilers and CMake
      run: |
         sudo apt update
         sudo apt install gcc-11 g++-11 cmake
         gcc --version
      shell: bash
    - name: Configure Hello World Library
      run:  | 
        cmake -H. \
              -Bbuild \
              -DCMAKE_CXX_COMPILER=gcc \
              -DBUILD_SHARED_LIBS=TRUE \
              -DCMAKE_INSTALL_PREFIX=${{ inputs.install_location }}
      shell: bash
    - name: Build Hello World Library
      run: cmake --build build
      shell: bash
    - name: Install Hello World Library
      run: cmake --build build --target install
      shell: bash
