name: "Install Hello World Library"
description: "Installs the Hello World Library"
inputs:
  install_location: 
    description: "Full path to where the library should be installed"
    required: false
    default: $HOME/install
  do_checkout:
    description: "Do we need to checkout Hello World Library?"
    required: false
    default: true
runs:
  using: "composite"
  env:
    work_directory: ${GITHUB_WORKSPACKE}/hello_world_library
    build_directory: ${GITHUB_WORKSPACE}/hello_world_library/build
  steps: 
    - name: Checkout Repository
      if: ${{ inputs.do_checkout }}
      uses: actions/checkout@v4
      with:
        repository: MultiprojectDevOps/hello_world_library
        path: ${work_directory}
    - name: Get Compilers and CMake
      run: |
         pwd
         sudo apt update
         sudo apt install gcc-11 g++-11 cmake
         gcc --version
      shell: bash
    - name: Configure Hello World Library
      run:  | 
        cmake -H${work_directory} \
              -B${build_directory} \
              -DCMAKE_CXX_COMPILER=gcc \
              -DBUILD_SHARED_LIBS=TRUE \
              -DCMAKE_INSTALL_PREFIX=${{ inputs.install_location }}
      shell: bash
    - name: Build Hello World Library
      run: cmake --build ${build_directory}
      shell: bash
    - name: Install Hello World Library
      run: cmake --build ${build_directory} --target install
      shell: bash
